# docker-compose -f LNX-docker-compose.yml up --build --exit-code-from app
version: '2.4'
services:
  app:
    environment:
    - MATLAB_LICENSE
    - MATLAB_USER
    image: raphaelguzman/matlab:${MATLAB_VERSION}-MIN
    user: ${MATLAB_UID}:${MATLAB_GID}
    working_dir: /main
    mac_address: $MATLAB_HOSTID
    volumes:
      - ./tests:/main/tests
      - ./GHToolbox.mltbx:/main/GHToolbox.mltbx
    command:
      - /bin/bash
      - -c
      - |
        matlab -nodisplay -r "
          import matlab.unittest.TestSuite;\
          matlab.addons.toolbox.installToolbox('GHToolbox.mltbx');\
          suite = TestSuite.fromFolder(pwd, 'IncludingSubfolders', true);\
          res = run(suite);\
          disp(res);\
          if all([res.Passed])  exit, else exit(1), end;\
        "